[Beat] additional logging
nodefluxio/weber pull request #182
Opened 2021-12-02 07:24 UTC by bagasteguhimani

## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

No INFO logs in the backend
minimal input 2 char for job title, company and name

## What is the new behavior?

Add INFO logs in backend
edit some log message
Edit minimal input to 5 char for job title, company, and name

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-12-02 07:45 UTC, sonadztux commented on backend/controllers/activity.go
> +	}).Info("[Controller] create activity start...")
Better sekalian dikasih nama blok fungsi/modelnya juga ga, sih? `[Controller: nama controller]` `[Model: nama model]` wdyt? @bagasteguhimani

2021-12-02 08:15 UTC, lazuardyk commented on backend/models/face_payment.go
> +	log.Info("[MODEL] create face payment account start...")
ini yg di model capslock semua [MODEL] yg di controller [Controller], diseragamin aja keknya gas

2021-12-02 08:41 UTC, sonadztux commented on backend/controllers/analytic.go
> +			"data":   data,
`data` ini kayaknya ga perlu deh, karena baru dideklarasi di line 45 `var data models.ServiceRequestResultData` dan belum ada isinya. wdyt? @bagasteguhimani

2021-12-02 08:44 UTC, sonadztux commented on backend/controllers/analytic.go
>  			"data":    data,
`data` yang di sini juga harusnya masih kosong

2021-12-02 08:46 UTC, sonadztux commented on backend/controllers/analytic.go
> +		"data":   data,
`data` di sini juga

2021-12-02 08:49 UTC, bagasteguhimani commented on backend/controllers/activity.go
> +	}).Info("[Controller] create activity start...")
Sebenarnya log message nya mirip nama blok fungsi masing2, tapi kalo mau dipermudah lagi sabi ditambah :+1:

2021-12-02 08:49 UTC, bagasteguhimani commented on backend/models/face_payment.go
> +	log.Info("[MODEL] create face payment account start...")
Okee zu, paling gw uppercase semua aja ya

2021-12-02 08:50 UTC, bagasteguhimani commented on backend/controllers/analytic.go
> +			"data":   data,
eh iya ding bakalan kosong isinya wkwk

2021-12-02 08:52 UTC, sonadztux commented on backend/controllers/analytic.go
>  			"data":    data,
`data` di sini juga

2021-12-02 08:53 UTC, sonadztux commented on backend/controllers/analytic.go
>  			"data":  dataAnalytic,
`data` di sini kayaknya better isinya `result` bukan `dataAnalytic`

2021-12-02 08:54 UTC, sonadztux commented on backend/controllers/analytic.go
>  			"data":  dataAnalytic,
cmiiw

2021-12-02 08:55 UTC, sonadztux commented on backend/controllers/analytic.go
>  			"data":  dataAnalytic,
atau kalau mau dua-duanya aja, tambahin `"result": result`

2021-12-02 08:56 UTC, sonadztux commented on backend/controllers/analytic.go
>  			"data":  dataAnalytic,
ini juga sama kaya https://github.com/nodefluxio/weber/pull/182/files?diff=unified&w=0#r760878864

2021-12-02 09:00 UTC, sonadztux commented on backend/controllers/ekyc.go
> +		"data":       inputData,
`inputData` buat EKYC ini isinya bakal gede termasuk bisa ada tiga base64 string gambar inputannya, mending show length nya aja bisa ga?

2021-12-02 09:17 UTC, sonadztux commented on backend/controllers/face_payment.go
>  			"data":       account,
Ini kalo emang not found yaudah berarti ga perlu show `"data": account` karena isinya kosong

2021-12-02 09:31 UTC, sonadztux commented on backend/controllers/face_payment.go
> +		"data":       inputDataToAnalytic,
Hmm gue bingung nih, `data` di sini maksudnya pengen show data akun yang baru pengen dibuat kan ya? Kalo gitu harusnya `newAccountData`, jadi `session_id` sama `phone` ga perlu. Tapi masalahnya di dalam `newAccountData` ada value base64 string image juga. Ada saran ga ya? @asyafalni @krismp @lazuardyk @bagasteguhimani

2021-12-02 09:32 UTC, sonadztux commented on backend/controllers/face_payment.go
> +		"data":       inputDataToAnalytic,
isi `inputDataToAnalytic` juga additional params sama base64 string image

2021-12-02 09:36 UTC, sonadztux commented on backend/controllers/face_payment.go
> +		"pin":        pin,
`pin` dishow gapapa kah ini?

2021-12-02 09:38 UTC, sonadztux commented on backend/controllers/face_payment.go
>  			"request_data": inputDataToAnalytic,
`inputDataToAnalytic` ini juga ya isinya base64 string image

2021-12-02 09:39 UTC, sonadztux commented on backend/controllers/face_payment.go
>  			"request_data": inputDataToAnalytic,
sama kaya https://github.com/nodefluxio/weber/pull/182/files?diff=unified&w=0#r760915347

2021-12-02 09:43 UTC, sonadztux commented on backend/controllers/innovation.go
> +		"data": data,
sama kaya https://github.com/nodefluxio/weber/pull/182/files?diff=unified&w=0#r760869464

2021-12-02 09:46 UTC, sonadztux requested changes
Kayaknya gue udah ngasih komen banyak tapi masih banyak juga file yang belum kereview :3 Yak kayaknya juga changes nya sama, kok, coba diteliti lagi `data` yang isinya kosong sama yang isinya ada base64 string image

2021-12-06 06:21 UTC, sonadztux approved these changes

2021-12-06 06:21 UTC, lazuardyk approved these changes

2021-12-06 06:22 UTC, merged