Refactored E-KYC Solution API for 1x Hit
nodefluxio/weber pull request #68
Opened 2021-11-02 13:17 UTC by lazuardyk

## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?
- e-KYC solution is 3x hit from front end
- using ```/services``` endpoint

## What is the new behavior?
- e-KYC solution is 1x hit from front end
- using ```/ekyc``` endpoint

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

Screenshot from Postman:
![Screenshot_1891](https://user-images.githubusercontent.com/10008683/139853905-eb1d7237-7f23-4bb2-afd5-195020e5f977.png)

Note that this endpoint will take more time than usual because we did a 3 requests to the cloud **sequentially**.

2021-11-03 02:17 UTC, sonadztux commented
Jadi berapa lama @lazuardyk?

2021-11-03 02:22 UTC, sonadztux commented on backend/README.md
> +  `/ekyc`
Zu minta tolong ini disesuain langsung biar jadi `/api/v1/ekyc` boleh ga?

2021-11-03 02:23 UTC, sonadztux commented on backend/README.md
> +{
`additional_params` kayaknya ga perlu jadi payload kalo emang isinya kosong

2021-11-03 02:30 UTC, sonadztux commented on backend/routes.go
> +		ekyc.POST("", controllers.GetEKYCResult)
Ini nama controllernya jadiin `CreateEKYCRequest` aja biar konsisten sama yang atasnya, semua nama controller buat request POST pakai prefix `Create`

2021-11-03 02:35 UTC, sonadztux requested changes

2021-11-03 02:35 UTC, sonadztux commented on backend/controllers/ekyc.go
> +func GetEKYCResult(ctx *gin.Context) {
Ini namanya ubah jadi `CreateEKYCRequest` gimana?

2021-11-03 03:26 UTC, rizkybaihaqy commented on backend/README.md
> +{
setuju

2021-11-03 09:47 UTC, sonadztux commented on backend/controllers/ekyc.go
> +}
Ini pindah ke models/ aja

2021-11-03 09:48 UTC, sonadztux commented on backend/controllers/ekyc.go
> +}
Buat face payment butuh ini juga, enaknya gimana ya biar ga buat baru (duplicate)?

2021-11-03 09:49 UTC, sonadztux commented on backend/controllers/ekyc.go
> +}
Face payment butuh ini juga

2021-11-03 09:50 UTC, lazuardyk commented on backend/controllers/ekyc.go
> +}
Utk sementara bisa dicopy dulu yak fungsinya, gw mau nyoba yang ubah ke async dulu, gw commit kalo udah selesai

2021-11-03 09:52 UTC, sonadztux commented on backend/controllers/ekyc.go
> +}
sama itu line 100 hapus aja Println nya

2021-11-04 02:22 UTC, krismp commented on backend/controllers/ekyc.go
> +}
`xRequestData` sm `xRequestInput` bedanya apa @lazuardyk ?

2021-11-04 02:24 UTC, krismp commented on backend/controllers/ekyc.go
> +		fmt.Println("Error during fetching API ocr ktp: ", err)
kita udh perlu nambahin log kayanya, nanti ini bisa masuk log severity error, gw bikin issue nya ya

2021-11-04 02:28 UTC, krismp commented on backend/controllers/ekyc.go
> +		fmt.Println("Error during fetching API ocr ktp: ", err)
https://github.com/nodefluxio/weber/issues/72

2021-11-04 08:49 UTC, lazuardyk commented on backend/README.md
> +  `/ekyc`
Done https://github.com/nodefluxio/weber/pull/68/commits/a64810572eccc2a1b447c4229fe473539bec5f1d

2021-11-04 09:08 UTC, lazuardyk commented on backend/README.md
> +{
Done https://github.com/nodefluxio/weber/pull/68/commits/e400e63487cc22534cd929b2e8d1be30a2796676

2021-11-04 09:10 UTC, lazuardyk commented on backend/routes.go
> +		ekyc.POST("", controllers.GetEKYCResult)
Done https://github.com/nodefluxio/weber/pull/68/commits/a64810572eccc2a1b447c4229fe473539bec5f1d

2021-11-04 09:11 UTC, lazuardyk commented on backend/controllers/ekyc.go
> +func GetEKYCResult(ctx *gin.Context) {
Done https://github.com/nodefluxio/weber/pull/68/commits/4359a53f5aa7ac3aadbfdb39d8af98296a3e7866

2021-11-04 09:12 UTC, lazuardyk commented on backend/controllers/ekyc.go
> +}
Ini gw pindahin ke ```analytic.go``` biar bisa dipake bareng
https://github.com/nodefluxio/weber/pull/68/commits/7a6882db18d9ad6612600217c0fd913c27abeaa5

2021-11-04 09:12 UTC, lazuardyk commented on backend/controllers/ekyc.go
> +}
Done https://github.com/nodefluxio/weber/pull/68/commits/7a6882db18d9ad6612600217c0fd913c27abeaa5

2021-11-04 09:13 UTC, lazuardyk commented on backend/controllers/ekyc.go
> +		fmt.Println("Error during fetching API ocr ktp: ", err)
Ok boleh, di issue dulu ya

2021-11-04 09:18 UTC, lazuardyk commented on backend/controllers/ekyc.go
> +}
@sonadztux terkait ini gaada hubungannnya sama database langsung sih, ditaro models aja?
sbnrnya yg di analytic.go juga ada 1 struct. tbh gw mikirnya jadi ribet soalnya kalo pindah2 file ke models wkwk

@krismp ```RequestInput``` itu ngebungkus ```RequestData```. karena lemparan dari frontend itu ada session id dan data

2021-11-04 09:29 UTC, lazuardyk commented
Udah gw update jadi async & resolve conflict. boleh dicoba dan dire-review ya @sonadztux @krismp @rizkybaihaqy

2021-11-05 03:08 UTC, sonadztux commented on backend/controllers/ekyc.go
> +}
Sip udah gue pake. Thanks @lazuardyk

2021-11-05 03:47 UTC, sonadztux approved these changes

2021-11-05 08:43 UTC, bagasteguhimani approved these changes
Work!

2021-11-05 10:32 UTC, merged